<a href="https://colab.research.google.com/github/Bhakti77/pandas/blob/main/practice_session1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

data = {
    'order_id':   [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
    'customer':   ['Aarav', 'Priya', 'Rohan', 'Sneha', 'Karan',
                   'Nisha', 'Amit', 'Pooja', 'Vikram', 'Anjali'],
    'city':       ['Mumbai', 'Pune', 'Delhi', 'Mumbai', 'Bangalore',
                   'Delhi', 'Pune', 'Mumbai', 'Bangalore', 'Delhi'],
    'category':   ['Electronics', 'Appliances', 'Electronics', 'Fitness',
                   'Electronics', 'Appliances', 'Fitness', 'Electronics',
                   'Fitness', 'Appliances'],
    'amount':     [75000, 3500, 82000, 1200, 45000,
                   4500, 6000, 45000, 3200, 12000],
    'status':     ['delivered', 'delivered', 'pending', 'delivered', 'cancelled',
                   'delivered', 'pending', 'delivered', 'cancelled', 'delivered']
}

df = pd.DataFrame(data)

In [2]:
#Find the total amount spent per city. Sort results from highest to lowest.
total_amount = df.groupby('city')['amount'].sum()
total_amount.sort_values(ascending=False)

city
Mumbai       121200
Delhi         98500
Bangalore     48200
Pune           9500
Name: amount, dtype: int64

In [6]:
#Find all orders where:
#status is 'delivered'
#amount is greater than 10000

stats = df[(df['status'] == 'delivered') & (df['amount'] > 10000)]
display(len(stats))

3

In [9]:
#Find the average amount per category, but only for delivered orders.

delivered_data = df[df['status']=='delivered'].groupby('category')['amount'].mean()
display(delivered_data)

category
Appliances      6666.666667
Electronics    60000.000000
Fitness         1200.000000
Name: amount, dtype: float64

In [14]:
#Add a new column called 'discount' to the DataFrame:
# If amount > 50000 → discount is 10%
# If amount > 10000 → discount is 5%
# Otherwise → discount is 0%

df['discount'] = df['amount'].apply(lambda x: 0.1* x if x>50000
                          else 0.05*x if x>10000 else 0)
df

   order_id customer       city     category  amount     status  discount
0       101    Aarav     Mumbai  Electronics   75000  delivered    7500.0
1       102    Priya       Pune   Appliances    3500  delivered       0.0
2       103    Rohan      Delhi  Electronics   82000    pending    8200.0
3       104    Sneha     Mumbai      Fitness    1200  delivered       0.0
4       105    Karan  Bangalore  Electronics   45000  cancelled    2250.0
5       106    Nisha      Delhi   Appliances    4500  delivered       0.0
6       107     Amit       Pune      Fitness    6000    pending       0.0
7       108    Pooja     Mumbai  Electronics   45000  delivered    2250.0
8       109   Vikram  Bangalore      Fitness    3200  cancelled       0.0
9       110   Anjali      Delhi   Appliances   12000  delivered     600.0

In [16]:
#Add another column called 'final_amount':

#final_amount = amount - discount

df['final_amount'] = df['amount'] - df['discount']
df

,order_id,customer,city,category,amount,status,discount,final_amount
0,101,Aarav,Mumbai,Electronics,75000,delivered,7500.0,67500.0
1,102,Priya,Pune,Appliances,3500,delivered,0.0,3500.0
2,103,Rohan,Delhi,Electronics,82000,pending,8200.0,73800.0
3,104,Sneha,Mumbai,Fitness,1200,delivered,0.0,1200.0
4,105,Karan,Bangalore,Electronics,45000,cancelled,2250.0,42750.0
5,106,Nisha,Delhi,Appliances,4500,delivered,0.0,4500.0
6,107,Amit,Pune,Fitness,6000,pending,0.0,6000.0
7,108,Pooja,Mumbai,Electronics,45000,delivered,2250.0,42750.0
8,109,Vikram,Bangalore,Fitness,3200,cancelled,0.0,3200.0
9,110,Anjali,Delhi,Appliances,12000,delivered,600.0,11400.0